### ISSUE TITLE
error  not running

### ISSUE THREAD

**Issue by vismayainnow8** [yuvraj24/react-native-stories-view#4] opened 2020-12-23 02:14 UTC
invalid hook error inside functionall component

**Comment by Girum** [comment] 2021-01-12 13:14
I'm with the same error:

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons

**Comment by aaronbesson** [comment] 2021-01-19 22:25
Same

**Comment by KarthikeyanM28** [comment] 2021-02-04 11:02
After call <StoryContainer ... app not working showing white screen only, doesn't through any error in metro bundler and console

**Comment by iamrameshwar** [comment] 2021-02-22 14:31
@yuvraj24 Any fix on this?

**Comment by noushad-techconfer** [comment] 2021-03-13 09:21
> same
clone this and use code of story view its working

**Comment by mishkeTz** [comment] 2021-03-20 20:24
bump

**Comment by mishkeTz** [comment] 2021-03-22 20:47
Using the same version of react in the project and what's in this package worked for me (i.e. 16.11.0)

**Comment by ketanuengage** [comment] 2021-04-10 10:08
> Invalid Hook call Error (issue with v.1.0.6 and 1.0.7)
> After call <StoryContainer ... app not working showing white screen only, doesn't through any error in metro bundler and console
> anyone address this issue.

Any fix for this?

**Comment by noushad-techconfer** [comment] 2021-04-10 11:54
use file fo this by creating this project to own folder

⁣Get BlueMail for Android ​

**Comment by ketanuengage** [comment] 2021-04-12 08:21
> use file fo this by creating this project to own folder ⁣Get BlueMail for Android ​
> […](#)
> On Apr 10, 2021, 3:38 PM, at 3:38 PM, ketanuengage ***@***.***> wrote: > Invalid Hook call Error (issue with v.1.0.6 and 1.0.7) > After call <StoryContainer ... app not working showing white screen only, doesn't through any error in metro bundler and console > anyone address this issue. Any fix for this? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817111944)

Didn't understand. Can you please elaborate?

**Comment by noushad-techconfer** [comment] 2021-04-12 08:32
contact me +91-8090973454

⁣Get BlueMail for Android ​

**Comment by nshadazhr** [comment] 2021-04-12 08:34
> Clone to own folder and use code of this ⁣Get BlueMail for Android ​
> […](#)
> On Apr 12, 2021, 1:51 PM, at 1:51 PM, ketanuengage ***@***.***> wrote: > use file fo this by creating this project to own folder ⁣Get BlueMail for Android ​> […](#) > On Apr 10, 2021, 3:38 PM, at 3:38 PM, ketanuengage ***@***.***> wrote: > Invalid Hook call Error (issue with v.1.0.6 and 1.0.7) > After call <StoryContainer ... app not working showing white screen only, doesn't through any error in metro bundler and console > anyone address this issue. Any fix for this? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)]([#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817111944)) Didn't understand. Can you please elaborate? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817598470)

**Comment by ketanuengage** [comment] 2021-04-12 08:37
> > Clone to own folder and use code of this ⁣Get BlueMail for Android ​
> > […](#)
> > On Apr 12, 2021, 1:51 PM, at 1:51 PM, ketanuengage _**@**_._**> wrote: > use file fo this by creating this project to own folder ⁣Get BlueMail for Android ​> […](#) > On Apr 10, 2021, 3:38 PM, at 3:38 PM, ketanuengage _**@**_.**_> wrote: > Invalid Hook call Error (issue with v.1.0.6 and 1.0.7) > After call <StoryContainer ... app not working showing white screen only, doesn't through any error in metro bundler and console > anyone address this issue. Any fix for this? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)]([#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817111944)) Didn't understand. Can you please elaborate? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817598470)

Okay. But how will that make any difference if I directly use NPM package ?

**Comment by noushad-techconfer** [comment] 2021-04-12 08:47
no any difference after cloning i am also using

⁣Get BlueMail for Android ​

**Comment by ketanuengage** [comment] 2021-04-12 11:46
I have cloned the project and now directly using the project locally. But now I am getting "Invalid hook call" error. I have attached the screenshot of the error as well.

![err](https://user-images.githubusercontent.com/81960114/114389522-b9e1d080-9bb2-11eb-98b9-8babbfed0ae9.jpeg)

**Comment by ketanuengage** [comment] 2021-04-13 07:00
> no any difference after cloning i am also using ⁣Get BlueMail for Android ​
> […](#)
> On Apr 12, 2021, 2:08 PM, at 2:08 PM, ketanuengage ***@***.***> wrote: > > Clone to own folder and use code of this ⁣Get BlueMail for Android​> > […](#) > > On Apr 12, 2021, 1:51 PM, at 1:51 PM, ketanuengage _**@**_._**> wrote: > use file fo this by creating this project to own folder ⁣Get BlueMail for Android ​> […](#) > On Apr 10, 2021, 3:38 PM, at 3:38 PM, ketanuengage _**@**_.**_> wrote: > Invalid Hook call Error (issue with v.1.0.6 and 1.0.7) > After call <StoryContainer ... app not working showing white screen only, doesn't through any error in metro bundler and console > anyone address this issue. Any fix for this? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)]([#4 (comment)]([#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817111944))) Didn't understand. Can you please elaborate? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)]([#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817598470)) Okay. But how will that make any difference if I directly use NPM package ? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/yuvraj24/react-native-stories-view/issues/4#issuecomment-817610547)

I have cloned the project locally but still I am getting white screen

**Comment by ketanuengage** [comment] 2021-04-13 07:18
@yuvraj24 Can you please look into these issues. It's not resolved for a long time.

**Comment by deleonjulio** [comment] 2021-04-20 04:33
still not working

**Comment by mtdst** [comment] 2021-05-20 06:07
still not working

**Comment by genesisbell** [comment] 2021-05-27 17:34
still not working

**Comment by A-M-Alizadeh** [comment] 2021-07-01 11:56
same error on react native 0.64 and react-native-stories-view "^1.0.7"
can anyone help plz ?

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

This error is located at:
    in StoryContainer (at App.js:77)
...

**Comment by yuvraj24** [comment] 2021-11-15 05:44
> Using the same version of react in the project and what's in this package worked for me (i.e. 16.11.0)

Consider using this approach.....if it helps....in the meanwhile will investigate the same !!

**Comment by neyosoft** [comment] 2021-11-20 22:29
The problem is because of version mismatch between the version of **metro-config** being used by the library and the version of been used by the project.

To check for the version of different _metro-config_ dependencies of the project

`yarn list metro-config`.

The solution is to **bump** the version of _metro_ and _metro-config._

**Comment by yuvraj24** [comment] 2021-12-03 13:08
The issue seems to be resolved thanks to the awesome work done by @vkoktashev. Have published a new version of [1.0.9](https://www.npmjs.com/package/react-native-stories-view)......update to the latest version now !!!

**Closed by yuvraj24** 2021-12-03 13:08 UTC
